#!/usr/bin/env python3
"""Generate the paper's partial-equilibrium Dynare models.

The paper points to Imrohoroglu and Tuzel (2014) for its standard production
and firm-productivity calibration. This generator uses their annual values,
and calibrates the quality ladder to a patent-event-rate proxy and the paper's
2.2% long-run growth target.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from scipy.optimize import brentq

GAMMA_GRID = (0.05, 0.10, 0.15, 0.20)
ROOT = Path(__file__).resolve().parent
ALPHA = 0.22
DELTA = 0.08
BETA = 0.96
EPSILON = 4.333333333333333
GROWTH = 0.022
# 36,457 of 80,986 R&D-positive manufacturing firm-years have a matched
# application-year patent event in the calibration sample.
P_SUCCESS = 36457 / 80986
RHO_OMEGA = 0.70
SIGMA_OMEGA = 0.268


def steady_state(gamma: float, p_success: float = P_SUCCESS) -> dict[str, float]:
    """Solve the stationary steady state at the empirical success-rate target."""
    if not 0.0 < p_success < 1.0:
        raise ValueError("p_success must be strictly between zero and one")
    quality_step = GROWTH / p_success
    lam = 1.0 + quality_step
    theta = (EPSILON - 1.0) / EPSILON
    sdf = BETA / (1.0 + GROWTH)
    k = ALPHA * theta / (1.0 / sdf - 1.0 + DELTA)
    y = 1.0
    labor = (y / k**ALPHA) ** (1.0 / (1.0 - ALPHA))
    wage = theta * (1.0 - ALPHA) / labor

    def state(z: float) -> tuple[float, float, float, float, float, float]:
        prob = p_success
        eta = prob / z**gamma
        invest = (DELTA + (lam - 1.0) * prob) * k
        dividends = y**theta - wage * labor - invest - z
        value = dividends / (1.0 - sdf * (1.0 + (lam - 1.0) * prob))
        residual = 1.0 - sdf * eta * gamma * z**(gamma - 1.0) * (lam - 1.0) * value
        return residual, prob, invest, dividends, eta, value

    z = brentq(lambda z_: state(z_)[0], 1e-10, 0.4)
    _, prob, invest, dividends, eta, value = state(z)
    if not (0.0 < prob < 1.0 and dividends > 0.0 and value > 0.0):
        raise ValueError(f"Inadmissible steady state for gamma={gamma}, eta={eta}")
    return {"k": k, "y": y, "labor": labor, "wage": wage, "z": z,
            "prob": prob, "invest": invest, "dividends": dividends, "value": value,
            "eta": eta, "lambda": lam, "quality_step": quality_step}


def render(gamma: float, p_success: float, rho: float, sigma: float) -> str:
    # These are the paper's stationary firm equations. The exogenous aggregate
    # output is normalized to one; wages and the SDF are fixed at their
    # calibrated steady-state values. There is no aggregate clearing block.
    ss = steady_state(gamma, p_success)
    eta = ss["eta"]
    lam = ss["lambda"]
    return f"""// Partial-equilibrium firm model from paper/main.tex, section Model.
// Generated by code/paper_simulation/generate_dynare.py.
// gamma={gamma}; eta={eta}; rho_omega={rho}; sigma_omega={sigma}

var y labor revenue k invest z innov_prob value dividends omega;
varexo eps_omega;
parameters alpha delta beta epsilon theta lambda gamma eta g lambda_sdf wage_bar rho_omega sigma_omega;

alpha = {ALPHA:.15g};
delta = {DELTA:.15g};
beta = {BETA:.15g};
epsilon = {EPSILON:.15g};
theta = (epsilon-1)/epsilon;
lambda = {lam:.15g};
gamma = {gamma:.12g};
eta = {eta:.12g};
g = {GROWTH:.15g};
lambda_sdf = beta/(1+g);
wage_bar = {ss['wage']:.15g}; // fixed steady-state wage; partial equilibrium
rho_omega = {rho:.12g};
sigma_omega = {sigma:.12g};

model;
  // Aggregate output Y_t is exogenous and normalized to one.
  y = omega*k(-1)^alpha*labor^(1-alpha);
  revenue = y^theta;
  wage_bar = theta*(1-alpha)*revenue/labor;

  // Stationary capital accumulation, accounting for expected quality growth.
  k*(1+(lambda-1)*innov_prob) = (1-delta)*k(-1) + invest;

  // Capital Euler equation and research return condition (paper equations 7-8).
  1 = lambda_sdf*(1-delta + alpha*theta*revenue(+1)/k);
  1 = lambda_sdf*eta*gamma*z^(gamma-1)*(lambda-1)*value(+1);

  // Stationary firm value and dividends. Innovation raises expected quality.
  value = dividends + lambda_sdf*(1+(lambda-1)*innov_prob)*value(+1);
  dividends = revenue - wage_bar*labor - invest - z;
  innov_prob = eta*z^gamma;

  // Firm-specific productivity is the only shock; no aggregate shocks/feedback.
  omega = omega(-1)^rho_omega*exp(eps_omega);
end;

initval;
  y = 1;
  labor = {ss['labor']:.15g};
  revenue = 1;
  k = {ss['k']:.15g};
  invest = {ss['invest']:.15g};
  z = {ss['z']:.15g};
  innov_prob = {ss['prob']:.15g};
  value = {ss['value']:.15g};
  dividends = {ss['dividends']:.15g};
  omega = 1;
  eps_omega = 0;
end;

steady;
check;
shocks;
  var eps_omega = sigma_omega^2;
end;
stoch_simul(order=1, loglinear, irf=0, nograph, noprint);
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--p-success", type=float, default=P_SUCCESS,
                        help="steady-state success-rate target from matched firm patent data")
    parser.add_argument("--rho", type=float, default=RHO_OMEGA,
                        help="TFP persistence (default: cited annual calibration, 0.70)")
    parser.add_argument("--sigma", type=float, default=SIGMA_OMEGA,
                        help="TFP innovation SD (default: cited annual calibration, 0.268)")
    args = parser.parse_args()
    if not 0 < args.p_success < 1 or not 0 <= args.rho < 1 or args.sigma <= 0:
        parser.error("require 0 < --p-success < 1, 0 <= --rho < 1, and --sigma > 0")
    out = ROOT / "generated"
    out.mkdir(exist_ok=True)
    for gamma in GAMMA_GRID:
        path = out / f"paper_partial_eq_g{int(gamma*100):02d}.mod"
        ss = steady_state(gamma, args.p_success)
        path.write_text(render(gamma, args.p_success, args.rho, args.sigma))
        print(f"{path}  Z_ss={ss['z']:.6g}  eta={ss['eta']:.6g}  "
              f"P_ss={ss['prob']:.6g}  lambda={ss['lambda']:.6g}")


if __name__ == "__main__":
    main()
