// ============================================================================
// cyclicality firm-level R&D model -- 2-state (K_tilde, a), gamma = 0.15
// GENERATED by code/dynare/gen_mod.py from the project steady state. Do not
// edit by hand; edit the generator. Shared by Dynare 6.5 and aether-macro.
//
// Monopolistic competition + CES demand make revenue concave in own output
// even under CRS production, so the marginal revenue product of capital
// declines in own K_tilde and K_tilde is a genuine state (the fix for the
// referee's degeneracy claim). A Hayashi/Jermann convex capital adjustment
// cost Phi=(phi/2)(I/K-dbar)^2*K makes capital predetermined and sluggish, so
// capx is a procyclical, persistent accelerator. Closure: aggregate demand
// Ybar is constant (idiosyncratic TFP shock); option (a) dividend keeps full
// real revenue.
// ============================================================================

var Y L rev K I Z P Lam V D q a;
varexo e;
parameters alpha delta beta eps lam gamma rho_a eta theta Ybar Wbar phi dbar;

alpha = 0.44;
delta = 0.12;
beta  = 0.96;
eps   = 4.33;
lam   = 1.0275;
gamma = 0.15;
rho_a = 0.625;
eta   = 1.55076985213;
theta = 0.769053117783;
Ybar  = 0.545485826736;
Wbar  = 0.693357713427;
phi   = 2;
dbar  = 0.142;

model;
  // 1. Production (CRS Cobb-Douglas)
  Y = exp(a)*K(-1)^alpha*L^(1-alpha);

  // 2. Perceived real revenue along the CES demand curve (Ybar taken as given)
  rev = Ybar^(1/eps)*Y^theta;

  // 3. Static labour FOC
  Wbar = theta*(1-alpha)*rev/L;

  // 4. Tobin's q = 1 + Phi_I,  Phi_I = phi*(I/K(-1) - dbar)
  q = 1 + phi*(I/K(-1) - dbar);

  // 5. Capital Euler with adjustment cost (Phi_K evaluated at t+1).
  //    Phi_K = (phi/2)*(I/K - dbar)^2 - phi*(I/K - dbar)*(I/K), here I=I(+1), K=K.
  q = Lam*( theta*alpha*rev(+1)/K
            - ( (phi/2)*(I(+1)/K - dbar)^2 - phi*(I(+1)/K - dbar)*(I(+1)/K) )
            + q(+1)*(1-delta) );

  // 6. Capital accumulation (stationarised)
  K*(1+(lam-1)*P) = (1-delta)*K(-1) + I;

  // 7. R&D FOC
  1 = Lam*eta*gamma*Z^(gamma-1)*(lam-1)*V(+1);

  // 8. Firm value (Lam*(1+(lam-1)*P) = beta)
  V = D + Lam*(1+(lam-1)*P)*V(+1);

  // 9. Dividend (option (a): full real revenue; net of adjustment cost Phi)
  D = rev - Wbar*L - I - (phi/2)*(I/K(-1) - dbar)^2*K(-1) - Z;

  // 10. Innovation probability
  P = eta*Z^gamma;

  // 11. Stationary stochastic discount factor (t -> t+1)
  Lam = beta/(1+(lam-1)*P);

  // 12. Log-TFP AR(1)
  a = rho_a*a(-1) + e;
end;

initval;
  a   = 0;
  Y   = 0.545485826736;
  L   = 0.338821127788;
  rev = 0.545485826736;
  K   = 1;
  I   = 0.142;
  Z   = 0.0121232087518;
  P   = 0.8;
  Lam = 0.939334637965;
  V   = 3.91095938899;
  D   = 0.15643837556;
  q   = 1;
  e   = 0;
end;

shocks;
  var e = 0.02^2;
end;

resid;
steady;
check;
stoch_simul(order=1, irf=40, nograph, noprint);
