"""
gen_mod.py
----------
Generate the Dynare/aether `.mod` files for the firm-level R&D model, one per
γ ∈ {0.05, 0.10, 0.15, 0.20}.

The model is the 2-state (K̃, a) firm problem under monopolistic competition
(option (a): the firm collects its full real revenue r̃; the markup profit
(1-θ)Ỹ accrues to the dividend). Concavity of revenue in own output — even
under CRS production — comes from the CES demand curve, which makes the
marginal revenue product of capital decline in own K̃, so K̃ is a genuine state.

Closure: each firm faces a *constant* aggregate demand Ȳ = Ỹ_SS (idiosyncratic
TFP shock; by the LLN the cross-sectional aggregate is constant). The firm's
perceived revenue is r̃ = Ȳ^{1/ε}·Ỹ^{(ε-1)/ε}, concave in own Ỹ.

Both the parameters AND the steady-state initval are written from the project's
own steady_state.solve(), so the .mod SS cannot drift from the Python SS.

Capital adjustment cost (Hayashi/Jermann q-theory):
  Φ(Ĩ,K̃) = (φ/2)(Ĩ/K̃ - δ̄)²·K̃,  δ̄ = δ + (λ-1)·P_SS
  Φ_I = φ(Ĩ/K̃ - δ̄)           Φ_K = (φ/2)(Ĩ/K̃-δ̄)² - φ(Ĩ/K̃-δ̄)(Ĩ/K̃)
Both Φ and Φ_I vanish at the SS (Ĩ/K̃ = δ̄), so Tobin's q = 1 and the steady
state is identical to the frictionless model.

Equilibrium system (Dynare timing; K(-1) ≡ predetermined K̃, K ≡ K̃'):
  1  Y    = exp(a)*K(-1)^alpha*L^(1-alpha)            production (CRS)
  2  rev  = Ybar^(1/eps)*Y^theta                      perceived revenue (CES demand)
  3  Wbar = theta*(1-alpha)*rev/L                     labour FOC
  4  q    = 1 + phi*(I/K(-1) - dbar)                  Tobin's q (Φ_I)
  5  q    = Lam*( theta*alpha*rev(+1)/K - PhiK(+1) + q(+1)*(1-delta) )  capital Euler
  6  K*(1+(lam-1)*P) = (1-delta)*K(-1) + I            capital accumulation
  7  1    = Lam*eta*gamma*Z^(gamma-1)*(lam-1)*V(+1)   R&D FOC
  8  V    = D + Lam*(1+(lam-1)*P)*V(+1)               firm value
  9  D    = rev - Wbar*L - I - Phi - Z                dividend (option (a), net of Φ)
  10 P    = eta*Z^gamma                               innovation probability
  11 Lam  = beta/(1+(lam-1)*P)                         stationary SDF (t->t+1)
  12 a    = rho_a*a(-1) + e                            log-TFP AR(1)
  (Phi, PhiK substituted inline.)

States: K (predetermined), a (exogenous). 12 endogenous, 1 shock.
"""

from __future__ import annotations
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PYDIR = HERE.parent / "python"
sys.path.insert(0, str(PYDIR))

from model.params import ModelParams, GAMMA_GRID          # noqa: E402
from model.steady_state import solve as solve_ss, check_ss  # noqa: E402

MODEL_BLOCK = """\
// ============================================================================
// cyclicality firm-level R&D model -- 2-state (K_tilde, a), gamma = {gamma}
// GENERATED by code/dynare/gen_mod.py from the project steady state. Do not
// edit by hand; edit the generator. Shared by Dynare 6.5 and aether-macro.
//
// Monopolistic competition + CES demand make revenue concave in own output
// even under CRS production, so the marginal revenue product of capital
// declines in own K_tilde and K_tilde is a genuine state (the fix for the
// referee's degeneracy claim). A Hayashi/Jermann convex capital adjustment
// cost Phi=(phi/2)(I/K-dbar)^2*K makes capital predetermined and sluggish, so
// capx is a procyclical, persistent accelerator. Closure: aggregate demand
// Ybar is constant (idiosyncratic TFP shock); option (a) dividend keeps full
// real revenue.
// ============================================================================

var Y L rev K I Z P Lam V D q a;
varexo e;
parameters alpha delta beta eps lam gamma rho_a eta theta Ybar Wbar phi dbar;

alpha = {alpha};
delta = {delta};
beta  = {beta};
eps   = {eps};
lam   = {lam};
gamma = {gamma};
rho_a = {rho_a};
eta   = {eta};
theta = {theta};
Ybar  = {Ybar};
Wbar  = {Wbar};
phi   = {phi};
dbar  = {dbar};

model;
  // 1. Production (CRS Cobb-Douglas)
  Y = exp(a)*K(-1)^alpha*L^(1-alpha);

  // 2. Perceived real revenue along the CES demand curve (Ybar taken as given)
  rev = Ybar^(1/eps)*Y^theta;

  // 3. Static labour FOC
  Wbar = theta*(1-alpha)*rev/L;

  // 4. Tobin's q = 1 + Phi_I,  Phi_I = phi*(I/K(-1) - dbar)
  q = 1 + phi*(I/K(-1) - dbar);

  // 5. Capital Euler with adjustment cost (Phi_K evaluated at t+1).
  //    Phi_K = (phi/2)*(I/K - dbar)^2 - phi*(I/K - dbar)*(I/K), here I=I(+1), K=K.
  q = Lam*( theta*alpha*rev(+1)/K
            - ( (phi/2)*(I(+1)/K - dbar)^2 - phi*(I(+1)/K - dbar)*(I(+1)/K) )
            + q(+1)*(1-delta) );

  // 6. Capital accumulation (stationarised)
  K*(1+(lam-1)*P) = (1-delta)*K(-1) + I;

  // 7. R&D FOC
  1 = Lam*eta*gamma*Z^(gamma-1)*(lam-1)*V(+1);

  // 8. Firm value (Lam*(1+(lam-1)*P) = beta)
  V = D + Lam*(1+(lam-1)*P)*V(+1);

  // 9. Dividend (option (a): full real revenue; net of adjustment cost Phi)
  D = rev - Wbar*L - I - (phi/2)*(I/K(-1) - dbar)^2*K(-1) - Z;

  // 10. Innovation probability
  P = eta*Z^gamma;

  // 11. Stationary stochastic discount factor (t -> t+1)
  Lam = beta/(1+(lam-1)*P);

  // 12. Log-TFP AR(1)
  a = rho_a*a(-1) + e;
end;

initval;
  a   = 0;
  Y   = {Y};
  L   = {L};
  rev = {rev};
  K   = {K};
  I   = {I};
  Z   = {Z};
  P   = {P};
  Lam = {Lam};
  V   = {V};
  D   = {D};
  q   = 1;
  e   = 0;
end;

shocks;
  var e = {sigma_a}^2;
end;

resid;
steady;
check;
stoch_simul(order=1, irf=40, nograph, noprint);
"""


def main():
    written = []
    for gamma in GAMMA_GRID:
        p = ModelParams(gamma=gamma)
        ss = solve_ss(p)                 # also sets p.eta, p.W_bar
        res = check_ss(ss, p, tol=1e-6)
        I_ss = ss.K_tilde * (p.delta + (p.lam - 1.0) * ss.P)
        txt = MODEL_BLOCK.format(
            gamma=f"{gamma:.10g}",
            alpha=f"{p.alpha:.10g}", delta=f"{p.delta:.10g}", beta=f"{p.beta:.10g}",
            eps=f"{p.eps:.10g}", lam=f"{p.lam:.10g}", rho_a=f"{p.rho_a:.10g}",
            eta=f"{p.eta:.12g}", theta=f"{p.theta:.12g}",
            Ybar=f"{ss.Y_tilde:.12g}", Wbar=f"{ss.W_bar:.12g}",
            phi=f"{p.phi:.10g}", dbar=f"{p.delta_bar:.12g}",
            sigma_a=f"{p.sigma_a:.10g}",
            Y=f"{ss.Y_tilde:.12g}", L=f"{ss.L:.12g}", rev=f"{ss.Y_tilde:.12g}",
            K=f"{ss.K_tilde:.12g}", I=f"{I_ss:.12g}", Z=f"{ss.Z_tilde:.12g}",
            P=f"{ss.P:.12g}", Lam=f"{ss.Lambda:.12g}", V=f"{ss.V_tilde:.12g}",
            D=f"{ss.D_tilde:.12g}",
        )
        fname = HERE / f"cyclicality_g{int(round(gamma*100)):02d}.mod"
        fname.write_text(txt)
        written.append((fname.name, gamma, p.eta, ss.Z_tilde, max(res.values())))
    print("Generated .mod files (SS verified from steady_state.solve):")
    for name, g, eta, Z, mr in written:
        print(f"  {name}  gamma={g:.2f}  eta={eta:.4f}  Z_SS={Z:.5f}  maxres={mr:.1e}")


if __name__ == "__main__":
    main()
