"""
perturbation.py
---------------
First-order perturbation of the firm-level R&D model, solved as a genuine
2-state (K̃, a) log-linear system.

This module is a thin wrapper around the **aether-macro** Klein (2000) solver.
The model is defined ONCE, in the Dynare/.mod files under code/dynare/
(generated by code/dynare/gen_mod.py from the project steady state). Both
Dynare 6.5 and aether-macro consume those same files, so the .mod is the single
source of truth and the two engines can be cross-checked against each other
(see code/dynare/engine_crosscheck.py).

Why this replaces the old analytic engine
------------------------------------------
The previous perturbation.py hard-coded a *degenerate* 1-state (a-only) system:
it set revenue = θỸ (linear in own output), so the marginal revenue product of
capital was independent of K̃, the value function was linear in K̃, and capital
never fluctuated. That is exactly the degeneracy the referee flagged ("Claim C").

The fix (approved): keep CRS Cobb-Douglas production, but model the firm as a
monopolistic competitor on the CES demand curve. Perceived real revenue
r̃ = Ȳ^{1/ε}·Ỹ^{(ε-1)/ε} is concave in own output even under CRS, so
MRPK = θα·r̃/K̃ declines in own K̃ and the capital Euler + accumulation make K̃ a
real state. Capital now responds to TFP shocks (the capx accelerator), while
R&D — tied to the smoothed firm value via the R&D FOC — responds much less
(R&D smoothing). The capx-vs-R&D ranking is therefore an endogenous property of
the solved model, not an assertion.

The Klein solution is the recursive law (level deviations from SS, in .mod
declaration order):

    y_t - y_ss = P @ (y_{t-1} - y_ss) + Q @ ε_t,   ε_t ~ N(0, σ_a²)

with all 11 endogenous variables (Y, L, rev, K, I, Z, P, Lam, V, D, a) carried
explicitly. Panel simulation iterates this recursion (see simulation.py).
"""

from __future__ import annotations
import os
import sys
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, List

import numpy as np

from .params import ModelParams
from .steady_state import SteadyState, solve as solve_ss

# ── Locate aether-macro (Klein perturbation engine) ───────────────────────────
_AETHER_HOME = os.environ.get(
    "AETHER_HOME",
    str(Path.home() / "Documents/Projects/personal/aether-macro"),
)
if _AETHER_HOME not in sys.path:
    sys.path.insert(0, _AETHER_HOME)

import aether                                       # noqa: E402
from aether.parsers.dynare import parse_mod_file    # noqa: E402
from aether.solvers.klein import linear_irf         # noqa: E402

# ── Location of the generated .mod files ──────────────────────────────────────
_DYNARE_DIR = Path(__file__).resolve().parents[2] / "dynare"


def _mod_path(gamma: float) -> Path:
    """Path to the generated .mod file for this gamma (grid: 0.05/0.10/0.15/0.20)."""
    return _DYNARE_DIR / f"cyclicality_g{int(round(gamma * 100)):02d}.mod"


@dataclass
class PerturbationSolution:
    """
    First-order (Klein) solution of the 2-state firm problem.

    The recursive law over level deviations (declaration order):
        y_t - y_ss = P @ (y_{t-1} - y_ss) + Q @ ε_t

    Attributes
    ----------
    ss        : SteadyState (project SS; matches the .mod SS to machine precision)
    p         : ModelParams
    names     : variable names in declaration order (= P/Q row order)
    idx       : name -> column index
    y_ss      : steady-state level vector (declaration order)
    P, Q      : Klein transition / shock-loading matrices
    klein     : the raw aether KleinSolution (for IRFs / diagnostics)
    n_stable  : number of stable eigenvalues reported by the solver
    """
    ss:       SteadyState
    p:        ModelParams
    names:    List[str]
    idx:      Dict[str, int]
    y_ss:     np.ndarray
    P:        np.ndarray
    Q:        np.ndarray
    klein:    object = field(repr=False, default=None)
    n_stable: int = 0

    # ── Convenience accessors ────────────────────────────────────────────────
    def ss_of(self, name: str) -> float:
        """Steady-state level of a variable."""
        return float(self.y_ss[self.idx[name]])

    def irf(self, shock_std: float = None, T: int = 40) -> Dict[str, np.ndarray]:
        """
        Impulse responses (level deviations from SS) to a one-time TFP shock.

        Returns a dict name -> array(T,). Divide by ss_of(name) for log/percent.
        """
        if shock_std is None:
            shock_std = self.p.sigma_a
        eps = np.zeros((T, 1))
        eps[0, 0] = shock_std
        traj = linear_irf(self.klein, eps)           # (T, n) level deviations
        return {nm: traj[:, j] for nm, j in self.idx.items()}

    def simulate_deviations(self, eps: np.ndarray) -> np.ndarray:
        """
        Iterate the Klein recursion for a panel of shock paths.

        Parameters
        ----------
        eps : array (N, T) of innovations ε_{i,t} (raw, in a-units)

        Returns
        -------
        array (N, T, n_vars) of level deviations y_{i,t} - y_ss
        """
        N, T = eps.shape
        n = self.P.shape[0]
        Pm = self.P
        Qv = self.Q[:, 0]                            # (n,)
        out = np.zeros((N, T, n))
        y_prev = np.zeros((N, n))
        for t in range(T):
            # y_t = P y_{t-1} + Q ε_t   (vectorised over firms)
            y_t = y_prev @ Pm.T + np.outer(eps[:, t], Qv)
            out[:, t, :] = y_t
            y_prev = y_t
        return out


def solve(p: ModelParams, verbose: bool = False) -> PerturbationSolution:
    """
    Solve the 2-state first-order perturbation via aether on the generated .mod.

    Parameters
    ----------
    p       : ModelParams (gamma must be on the grid 0.05/0.10/0.15/0.20)
    verbose : print diagnostics

    Returns
    -------
    PerturbationSolution
    """
    mod = _mod_path(p.gamma)
    if not mod.exists():
        raise FileNotFoundError(
            f"Missing {mod.name}. Generate the .mod files first:\n"
            f"    python3 {_DYNARE_DIR / 'gen_mod.py'}"
        )

    # Project steady state (independent of aether; used for downstream API and
    # to confirm the .mod SS the engine recovers).
    ss = solve_ss(p, verbose=False)

    sir = parse_mod_file(str(mod), name=mod.stem)
    rep = aether.solve(sir)
    if not rep.ok or rep.klein is None:
        raise RuntimeError(
            f"aether failed to solve {mod.name} (stage={rep.failed_stage}): "
            f"{rep.error}"
        )

    names = [v.name for v in sir.variables if v.kind == "endogenous"]
    idx = {nm: i for i, nm in enumerate(names)}
    y_ss = np.asarray(rep.y_ss, dtype=float)
    k = rep.klein
    Pm = np.asarray(k.P, dtype=float)
    Qv = np.asarray(k.Q, dtype=float)

    # Cross-check: engine SS must match the project SS (defensive).
    ss_map = {"Y": ss.Y_tilde, "L": ss.L, "rev": ss.Y_tilde, "K": ss.K_tilde,
              "Z": ss.Z_tilde, "P": ss.P, "Lam": ss.Lambda, "V": ss.V_tilde,
              "D": ss.D_tilde}
    ss_gap = max(abs(y_ss[idx[nm]] - val) for nm, val in ss_map.items())
    if ss_gap > 1e-8:
        raise RuntimeError(
            f"{mod.name}: engine SS disagrees with project SS by {ss_gap:.2e}."
        )

    if verbose:
        irf0 = linear_irf(k, np.r_[[[p.sigma_a]], np.zeros((39, 1))])
        def pct(nm):
            return irf0[0, idx[nm]] / y_ss[idx[nm]] * 100.0
        print(f"\nPerturbation (2-state, γ={p.gamma:.2f}) via aether:")
        print(f"  engine SS gap vs project SS = {ss_gap:.2e}")
        print(f"  n_stable = {k.n_stable}")
        print(f"  impact to +{p.sigma_a:.0%} TFP: "
              f"Y={pct('Y'):+.2f}%  K={pct('K'):+.2f}%  I(capx)={pct('I'):+.2f}%  "
              f"Z(R&D)={pct('Z'):+.2f}%  V={pct('V'):+.2f}%")
        print(f"  capx/R&D response ratio = {pct('I')/pct('Z'):.1f}×  "
              f"(accelerator vs smoothing)")

    return PerturbationSolution(
        ss=ss, p=p, names=names, idx=idx, y_ss=y_ss,
        P=Pm, Q=Qv, klein=k, n_stable=int(k.n_stable),
    )
