"""
40_simulate_model.py
--------------------
Master script: solve the 2-state (K̃, a) firm-level R&D model and reproduce the
Table-4 moments, with the capx accelerator vs R&D smoothing contrast.

The model (see code/dynare/*.mod, generated by gen_mod.py): CRS Cobb-Douglas
production, monopolistic competition on a CES demand curve (so revenue is concave
in own output and the marginal revenue product of capital declines in own K̃),
plus a Hayashi/Jermann capital adjustment cost. This makes K̃ a genuine state
(fixing the referee's degeneracy) and capx a procyclical, persistent accelerator.

Three solution methods (all 2-state), cross-checked against each other and, for
perturbation, against Dynare (code/dynare/engine_crosscheck.py):
  1. First-order perturbation (aether-macro / Klein, on the Dynare .mod)
  2. Value function iteration  (grid time iteration on (K̃, a))
  3. Chebyshev projection       (collocation on (K̃, a))

For each method × γ ∈ {0.05, 0.10, 0.15, 0.20}:
  - solve, simulate N=1000 firms × T=200 periods,
  - estimate the Table-4 FE regressions plus the capx-margin accelerator metrics.

Outputs:
  results/model_table4.xlsx / .md  — Table 4 equivalents + accelerator metrics
  results/figures/model_*.png      — policy slices, β-vs-γ, capx vs R&D responses
"""

import sys, time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

SCRIPT_DIR  = Path(__file__).parent
PROJECT_DIR = SCRIPT_DIR.parent.parent
RESULTS_DIR = PROJECT_DIR / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
RESULTS_DIR.mkdir(exist_ok=True); FIGURES_DIR.mkdir(exist_ok=True)
sys.path.insert(0, str(SCRIPT_DIR))

from model.params       import ModelParams
from model.steady_state import solve as solve_ss, check_ss
from model              import perturbation, vfi, projection
from model.simulation   import (simulate_from_perturbation,
                                 simulate_from_vfi,
                                 simulate_from_projection)
from model.estimation   import (estimate_table4, format_table4,
                                 compare_to_targets, TABLE4_TARGETS)

GAMMA_GRID = [0.05, 0.10, 0.15, 0.20]


def log(msg: str):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


# ════════════════════════════════════════════════════════════════════════════
# 1. Steady-state verification
# ════════════════════════════════════════════════════════════════════════════
log("=" * 70); log("Step 1: Steady-state verification"); log("=" * 70)
for gamma in GAMMA_GRID:
    p = ModelParams(gamma=gamma); ss = solve_ss(p)
    res = check_ss(ss, p, tol=1e-6); mr = max(res.values())
    log(f"  γ={gamma:.2f} | K̃={ss.K_tilde:.3f} Z̃={ss.Z_tilde:.5f} Ṽ={ss.V_tilde:.4f} "
        f"η={ss.eta:.4f} | max_resid={mr:.1e} {'✓' if mr < 1e-5 else '⚠'}")


# ════════════════════════════════════════════════════════════════════════════
# 2. Solve all three methods for each gamma
# ════════════════════════════════════════════════════════════════════════════
log("\n" + "=" * 70); log("Step 2: Solving model (3 methods × 4 γ)"); log("=" * 70)
solutions = {"perturbation": {}, "vfi": {}, "projection": {}}

for gamma in GAMMA_GRID:
    p = ModelParams(gamma=gamma)
    log(f"\n  γ = {gamma:.2f}")

    t0 = time.time()
    sol = perturbation.solve(p)
    irf = sol.irf()
    pct = lambda v: irf[v][0] / sol.ss_of(v) * 100
    log(f"    Perturbation: impact capx={pct('I'):+.2f}% R&D={pct('Z'):+.2f}% "
        f"(ratio {pct('I')/pct('Z'):.1f}×) ({time.time()-t0:.1f}s)")
    solutions["perturbation"][gamma] = sol

    t0 = time.time()
    sol = vfi.solve(p, tol=1e-6, max_iter=400, relax=0.5)
    z_ss = float(np.ravel(sol.policy_Z(ss.K_tilde, 1.0))[0])
    log(f"    VFI: Z̃(K_ss,a_ss)={z_ss:.5f} (SS {sol.ss.Z_tilde:.5f}) ({time.time()-t0:.1f}s)")
    solutions["vfi"][gamma] = sol

    t0 = time.time()
    sol = projection.solve(p, n_proj=8, tol=1e-7, max_iter=400, relax=0.5)
    z_ss = float(np.ravel(sol.policy_Z(sol.ss.K_tilde, 1.0))[0])
    log(f"    Projection: Z̃(K_ss,a_ss)={z_ss:.5f} (SS {sol.ss.Z_tilde:.5f}) ({time.time()-t0:.1f}s)")
    solutions["projection"][gamma] = sol


# ════════════════════════════════════════════════════════════════════════════
# 3. Policy-function slices (Z̃ vs a at K̃_SS; K̃' vs K̃ at a_SS)
# ════════════════════════════════════════════════════════════════════════════
log("\n" + "=" * 70); log("Step 3: Policy-function plots"); log("=" * 70)
for gamma in GAMMA_GRID:
    sp = solutions["perturbation"][gamma]; sv = solutions["vfi"][gamma]
    sr = solutions["projection"][gamma]; ss = sv.ss
    a_lo, a_hi = sv.a_grid[0], sv.a_grid[-1]
    a_plot = np.linspace(a_lo * 1.01, a_hi * 0.99, 60)
    K_plot = np.linspace(sv.K_grid[0] * 1.01, sv.K_grid[-1] * 0.99, 60)

    # perturbation policies via the linear law around SS (level deviations)
    iK, iZ, ia = sp.idx["K"], sp.idx["Z"], sp.idx["a"]
    def pert_Z_of_a(av):
        return ss.Z_tilde + sp.P[iZ, ia] * np.log(av)      # a-dev = log a
    def pert_Knext_of_K(Kv):
        return ss.K_tilde + sp.P[iK, iK] * (Kv - ss.K_tilde)

    fig, ax = plt.subplots(1, 2, figsize=(11, 4))
    ax[0].plot(a_plot, pert_Z_of_a(a_plot) * 1000, "--", color="#1f77b4", lw=2, label="Perturbation")
    ax[0].plot(a_plot, sv.policy_Z(np.full_like(a_plot, ss.K_tilde), a_plot) * 1000,
               color="#2ca02c", lw=2, label="VFI")
    ax[0].plot(a_plot, sr.policy_Z(np.full_like(a_plot, ss.K_tilde), a_plot) * 1000,
               ":", color="#d62728", lw=2, label="Projection")
    ax[0].set_xlabel("TFP a"); ax[0].set_ylabel("R&D Z̃ (×1000)")
    ax[0].set_title(f"R&D policy Z̃(a) at K̃_SS, γ={gamma}"); ax[0].legend(); ax[0].grid(alpha=0.3)

    ax[1].plot(K_plot, pert_Knext_of_K(K_plot), "--", color="#1f77b4", lw=2, label="Perturbation")
    ax[1].plot(K_plot, sv.policy_Knext(K_plot, np.ones_like(K_plot)),
               color="#2ca02c", lw=2, label="VFI")
    ax[1].plot(K_plot, sr.policy_Knext(K_plot, np.ones_like(K_plot)),
               ":", color="#d62728", lw=2, label="Projection")
    ax[1].plot(K_plot, K_plot, color="k", lw=0.7, alpha=0.5)
    ax[1].set_xlabel("capital K̃"); ax[1].set_ylabel("next capital K̃'")
    ax[1].set_title(f"Capital policy K̃'(K̃) at a_SS, γ={gamma}"); ax[1].legend(); ax[1].grid(alpha=0.3)
    plt.tight_layout()
    fig.savefig(FIGURES_DIR / f"model_policy_gamma{int(gamma*100):02d}.png", dpi=140)
    plt.close(fig)
log(f"  Saved policy-function plots to {FIGURES_DIR}")


# ════════════════════════════════════════════════════════════════════════════
# 4. Simulate and estimate
# ════════════════════════════════════════════════════════════════════════════
log("\n" + "=" * 70); log("Step 4: Simulation and estimation"); log("=" * 70)
all_results = []
SIM_FUNCS = {"perturbation": simulate_from_perturbation,
             "vfi": simulate_from_vfi, "projection": simulate_from_projection}

for method, sim_func in SIM_FUNCS.items():
    log(f"\n  Method: {method}")
    for gamma in GAMMA_GRID:
        sol = solutions[method].get(gamma)
        if sol is None:
            log(f"    γ={gamma:.2f}: skipped"); continue
        t0 = time.time()
        panel = sim_func(sol, seed=42)
        res = estimate_table4(panel, gamma=gamma, method=method)
        all_results.append(res)
        tgt = TABLE4_TARGETS.get(gamma, {}).get("beta_A", float("nan"))
        log(f"    γ={gamma:.2f}: β_R&D={res['beta_A']:.3f} (paper {tgt:.3f}) | "
            f"i/k acc={res['beta_ik']:+.4f} | z|i={res['beta_zi']:+.4f} | "
            f"β_share={res['beta_B']:+.5f} [{time.time()-t0:.1f}s, N={panel.N}×{panel.T}]")


# ════════════════════════════════════════════════════════════════════════════
# 5. Save results
# ════════════════════════════════════════════════════════════════════════════
log("\n" + "=" * 70); log("Step 5: Saving results"); log("=" * 70)
table4_df = format_table4(all_results)
comparison_df = compare_to_targets(all_results)

out_xlsx = RESULTS_DIR / "model_table4.xlsx"
with pd.ExcelWriter(out_xlsx, engine="openpyxl") as writer:
    table4_df.to_excel(writer, sheet_name="Table4", index=False)
    comparison_df.to_excel(writer, sheet_name="vs_targets", index=False)
log(f"  Saved: {out_xlsx}")

out_md = RESULTS_DIR / "model_table4.md"
with open(out_md, "w") as f:
    f.write("# Model simulation — Table 4 equivalents (2-state model)\n\n")
    f.write("Model: CRS production + CES demand (concave revenue) + capital "
            "adjustment cost. K̃ is a genuine state; capx is a procyclical "
            "accelerator and R&D is smoothed. β_R&D is reported as the model's "
            "own (untuned) prediction; ρ_a is NOT tuned to the paper targets.\n\n")
    f.write("Columns: beta_A = R&D smoothing (Δlog Z ~ Δlog PY, in (0,1)); "
            "beta_capx = capx growth slope (noisy margin); "
            "beta_ik = investment-rate accelerator (i/k ~ Δlog sales, >0); "
            "beta_zi = R&D/total-investment ratio (~ Δlog sales, <0 = hypothesis 2).\n\n")
    f.write("## Regression results\n\n")
    f.write(table4_df.to_markdown(index=False))
    f.write("\n\n## Comparison to paper β_A targets\n\n")
    f.write(comparison_df.to_markdown(index=False))
    f.write("\n\n### Paper β_A targets (for reference only; not tuned to)\n\n")
    tgt_rows = [{"gamma": g, "beta_A": v["beta_A"], "beta_B": v["beta_B"]}
                for g, v in TABLE4_TARGETS.items()]
    f.write(pd.DataFrame(tgt_rows).to_markdown(index=False))
log(f"  Saved: {out_md}")
log("\nTable 4:"); print(table4_df.to_string(index=False))


# ════════════════════════════════════════════════════════════════════════════
# 6. Figures: β_R&D vs γ (3 methods) and capx-vs-R&D impact responses
# ════════════════════════════════════════════════════════════════════════════
fig, ax = plt.subplots(figsize=(7, 4))
colors = {"perturbation": "#1f77b4", "vfi": "#2ca02c", "projection": "#d62728"}
markers = {"perturbation": "o", "vfi": "s", "projection": "^"}
for method in ["perturbation", "vfi", "projection"]:
    sub = [r for r in all_results if r["method"] == method and not np.isnan(r["beta_A"])]
    if sub:
        ax.plot([r["gamma"] for r in sub], [r["beta_A"] for r in sub],
                color=colors[method], marker=markers[method], label=method.capitalize(), lw=2, ms=7)
tgt_g = sorted(TABLE4_TARGETS); ax.plot(tgt_g, [TABLE4_TARGETS[g]["beta_A"] for g in tgt_g],
        "k--", marker="D", lw=1.5, label="Paper target")
ax.set_xlabel("γ (R&D curvature)"); ax.set_ylabel("β_R&D  (Δlog Z ~ Δlog PY)")
ax.set_title("R&D smoothing vs γ: 3 methods vs paper"); ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); fig.savefig(FIGURES_DIR / "model_beta_vs_gamma.png", dpi=140); plt.close(fig)

# capx vs R&D impulse responses (perturbation), γ=0.10
sp = solutions["perturbation"][0.10]; irf = sp.irf(T=30)
fig, ax = plt.subplots(figsize=(7, 4))
for v, c, lab in [("I", "#d62728", "capx Ĩ"), ("K", "#9467bd", "capital K̃"),
                  ("Z", "#1f77b4", "R&D Z̃"), ("Y", "#2ca02c", "output Ỹ")]:
    ax.plot(np.arange(len(irf[v])), irf[v] / sp.ss_of(v) * 100, lw=2, color=c, label=lab)
ax.axhline(0, color="k", lw=0.6); ax.set_xlabel("years after +2% TFP shock")
ax.set_ylabel("% deviation from SS")
ax.set_title("Accelerator vs smoothing: capx responds more than R&D (γ=0.10)")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout(); fig.savefig(FIGURES_DIR / "model_capx_vs_rnd_irf.png", dpi=140); plt.close(fig)
log(f"  Saved figures to {FIGURES_DIR}")

log("\n" + "=" * 70); log("DONE"); log("=" * 70)
